name: PDFTranslator
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip
    - pip:
          - huggingface_hub
          - tqdm
          - langchain
          - langchain-ollama
          - langchain_community
          - langchain-text-splitters
          - PyMuPDF
          - nltk
          - Pillow
          - python-docx
          - reportlab