# environment.yml
# Define el entorno conda para el proyecto PDFTranslator.
# Este archivo prioriza la instalación de paquetes Python a través de pip
# dentro del entorno conda, manteniendo solo las dependencias base y binarias
# esenciales en la sección de conda.
#
# Para crear el entorno: conda env create -f environment.yml
# Para activar el entorno: conda activate PDFTranslator

name: PDFTranslator
channels:
  - conda-forge  # Prioriza conda-forge para una mayor disponibilidad de paquetes
  - defaults

dependencies:
  # Dependencias base esenciales para el entorno conda
  - python=3.12
  - pip
  # ffmpeg es una dependencia binaria requerida por moviepy.
  # Es mejor gestionarla a través de conda o del sistema operativo.
  - ffmpeg

  # Todas las demás dependencias de Python se gestionan a través de pip
  - pip:
      # Paquetes movidos de la sección principal de dependencias de conda:
      - pillow>=11.1.0,<12.0.0 # MOVED FROM CONDA - Pip will now install a version compatible with 'together'
      - nltk                # Natural Language Toolkit
      - reportlab           # Generación de PDF (a menudo usado con docx)
      - tqdm                # Barras de progreso
      - pandas              # Manipulación de datos (usado en streamlit_ui)
      - beautifulsoup4      # Análisis HTML/XML (para EPUB)
      - ebooklib            # Manejo de archivos EPUB
      - protobuf            # Buffers de protocolo (dependencia común)

      # Paquetes que ya estaban en la sección pip o comentados:
      # Langchain ecosystem
      - langchain
      - langchain-ollama
      - langchain_community
      - langchain-google-genai
      - langchain-text-splitters

      # Otras librerías del proyecto
      - python-docx           # Manejo de documentos Word
      - supabase~=2.13.0      # Cliente Supabase con restricción de versión
      - huggingface_hub       # Del environment.yml original
      - openai                # Cliente OpenAI (asumiendo que es necesario)
      - pymupdf==1.25.0       # Manejo de PDF (especificando versión vía pip)
      - google-generativeai   # Librería de Google para interacciones con IA
      - ollama                # Cliente Ollama
      - streamlit             # Framework para UI web
      - transformers          # Librería de Hugging Face para modelos
      - groq                  # Cliente Groq
      - pymongo               # Cliente MongoDB
      - together              # Cliente Together AI
      - tiktoken              # Utilidad de tokens
      - moviepy               # Edición de video (requiere ffmpeg)

# Notas:
# 1. Se han movido casi todos los paquetes Python a la sección `pip:`.
# 2. `python`, `pip` y `ffmpeg` se mantienen en la sección principal de `dependencies`
#    porque son esenciales para configurar el entorno y las herramientas binarias.
# 3. Esta configuración centraliza la gestión de versiones de paquetes Python en pip,
#    lo que puede simplificar la resolución de dependencias.
# 4. Para aplicar estos cambios, actualiza tu entorno conda.